name: taskthree
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  material_color_utilities: ^0.12.0
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/bro.png
    - asset/codewithharry.jpeg
    - asset/gt.jpeg
    - asset/pubg.jpeg
    - asset/techwiser.jpeg
    - asset/ytlogo.jpg